swagger: "2.0"
info:
  version: 1.2.1
  title: MTA Deployer REST Protocol
host: example.com
basePath: /rest/
securityDefinitions:
  basic:
    type: basic
  oauth2:
    type: oauth2
    tokenUrl: https://uaa.bosh-lite.com/oauth/token
    flow: password
    scopes: {}
security:
  - oauth2: []
schemes:
  - https
consumes:
  - application/xml
produces:
  - application/xml
paths:
  /configuration-entries/purge:
    post:
      operationId: PurgeConfiguration
      responses:
        204:
          description: No Content
    parameters:
      - $ref: "#/parameters/org"
      - $ref: "#/parameters/space"
parameters:
  org:
    name: org
    in: query
    required: true
    type: string
  space:
    name: space
    in: query
    required: true
    type: string
